### PR TITLE
Update protocol from wlroots

### PR DESCRIPTION
**Pull request by Riey**

### CODE REVIEW

**Comment by grelltrier** [comment]
Hi,
thank you for the pull request and please excuse the long time it took me to respond to you.

I created this crate for the keyboard application I am writing, which is meant for mobile Linux and phosh/phoc as the compositor so it uses the same protocols as squeekboard does. If I understand it correctly, Purism adapted the protocols to their needs for the keyboard. They worked with wlroots in 2018 resulting in ([this](https://github.com/swaywm/wlroots/blob/master/protocol/input-method-unstable-v2.xml)). I am guessing, that is where you got your version for the pull request?
The version Purism is using for squeekboard can be found [here ](https://source.puri.sm/Librem5/squeekboard/-/blob/master/protocols/input-method-unstable-v2.xml) and was last changed one month ago, which leads me to believe it is up to date.

Honestly I am not involved with the development of the protocols and what the status of them is. Do you know more about it?

I will be busy with university until the end of April and won't find the time to look into this more. If both versions of the protocol are needed, I can look into using feature flags to select the version after I am done with university.

**Comment by Riey** [comment]
Oh I didn't know that background I just use this protocol for connect my IME with sway

> They worked with wlroots in 2018 resulting in (this). I am guessing, that is where you got your version for the pull request?

Yes I get this from wlroots master

> Honestly I am not involved with the development of the protocols and what the status of them is. Do you know more about it?

I don't know about purism's plan but on the sway side, there are [input method](https://github.com/swaywm/sway/pull/4932) and [popup](https://github.com/swaywm/sway/pull/5890) pr waiting for merge

**Comment by Riey** [comment]
I think this protocol is still experimental and unstable so if you don't want apply this state feel free to close this

**Comment by grelltrier** [comment]
Alright, I'll keep it open so I don't forget to look into it later. I should also mention this being the Purism version in the README.md

**Comment by pentamassiv** [comment]
The newest version of this crate uses the newest version of the protocol from wlroots. Sorry it took this long

**Pull request closed without merging**
